name: Shell Scripts Unit Testing

on:
  pull_request:
    branches: [master]

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install Pytest dependencies
        run: |
          python -m pip install pytest
          python -m pip install -e excel2sbol
      - name: Test with pytest
        run: |
          cd ./excel2sbol
          python -m pytest -vv -s
